### ISSUE TITLE
email is needed

### ISSUE THREAD

**Issue by Miever1** [JoyShaheb/joyshaheb#1]

**Comment by Miever1** [comment]
hey,bro
    I think you can add your email so that we can contact you with email, here twitter is forbiden

**Comment by JoyShaheb** [comment]
> hey,bro
> I think you can add your email so that we can contact you with email, here twitter is forbiden

sure, I'm working on my portfolio at the moment, There will be  a lot of changes. Thank you for the well wishes & suggestions 🌹
